// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote.proto

package com.sophon.schedule.remote.grpc;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string clientIp = 8;</code>
   * @return The clientIp.
   */
  String getClientIp();
  /**
   * <code>string clientIp = 8;</code>
   * @return The bytes for clientIp.
   */
  com.google.protobuf.ByteString
      getClientIpBytes();

  /**
   * <code>string extra = 5;</code>
   * @return The extra.
   */
  String getExtra();
  /**
   * <code>string extra = 5;</code>
   * @return The bytes for extra.
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  /**
   * <code>.google.protobuf.Any body = 4;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>.google.protobuf.Any body = 4;</code>
   * @return The body.
   */
  com.google.protobuf.Any getBody();
  /**
   * <code>.google.protobuf.Any body = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
