// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote.proto

package com.sophon.schedule.remote.grpc;

public final class Remote {
  private Remote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014remote.proto\032\031google/protobuf/any.prot" +
      "o\"\\\n\007Payload\022\014\n\004type\030\003 \001(\t\022\020\n\010clientIp\030\010" +
      " \001(\t\022\r\n\005extra\030\005 \001(\t\022\"\n\004body\030\004 \001(\0132\024.goog" +
      "le.protobuf.Any2*\n\007Request\022\037\n\007request\022\010." +
      "Payload\032\010.Payload\"\0002:\n\rRequestStream\022)\n\r" +
      "requestStream\022\010.Payload\032\010.Payload\"\000(\0010\001B" +
      "#\n\037com.sophon.schedule.remote.grpcP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_Payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new String[] { "Type", "ClientIp", "Extra", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
